# permissions for end users to view ossbindingoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ossbindingoperator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oss-bind-operator
    app.kubernetes.io/part-of: oss-bind-operator
    app.kubernetes.io/managed-by: kustomize
  name: ossbindingoperator-viewer-role
rules:
- apiGroups:
  - opeartor.learn.io.oss.controller.learn
  resources:
  - ossbindingoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opeartor.learn.io.oss.controller.learn
  resources:
  - ossbindingoperators/status
  verbs:
  - get
